### PR TITLE
Interpolate args into single string

### PR DESCRIPTION
**Pull request by rwstauner**
Multiple arguments will not do what you want.

### CODE REVIEW

**Comment by pascalw** [comment]
Hi @rwstauner can you please explain the difference between `$@` and `$*` in this case? According to [this](http://wiki.bash-hackers.org/scripting/posparams#mass_usage) it doesn't make a difference when the variable is not quoted.

**Comment by rwstauner** [comment]
It _is_ quoted; it is part of a large, multi-line, double-quoted string.

``` bash
*$ cat ~/tmp/show.bash ; bash ~/tmp/show.bash
show () { for arg in "$@"; { printf "«%q»\n" "$arg"; } }
demo () {
  show " at
  $@
  multi line";
  show " asterisk
  $*
  multi line";
}
demo a b c
«$' at\n  a'»
«b»
«$'c\n  multi line'»
«$' asterisk\n  a b c\n  multi line'»
```

**Comment by rwstauner** [comment]
i just pushed a better fix.
While $\* would at least not break the script open like $@ did, may as well preserve the arguments so that something like `run-containerized touch "hi there.txt"` works as expected.

**Comment by pascalw** [comment]
@rwstauner thanks for explaining. I like that this change would make passing arguments to the script more intuitive (no need to quote), but it would be a breaking change.

For example currently passing `mvn clean install` to the script is done as `run-containerized 'mvn clean install'`. This change would break such jobs because that would be interpreted as a single command. So even though the change you're proposing here is technically correct and better than what we have right now I'm afraid I can't merge it.

For reference, if you'd want to run a command like `touch "hi there.txt"` with the current version you'd have to pass it quoted like `run-containerized 'touch "hi there.txt"'`.

**Comment by rwstauner** [comment]
Yes, you're right.  For back-compat the original fix was better, so I restored that one.

**Comment by pascalw** [comment]
Ok but with that the example you provided `run-containerized touch "hi there.txt` does not behave any different than with the original code.

This is all quite confusing because the arguments to `run-containerized` are passed as the value of the `bash -c` argument which in turn is passed as the argument to `docker run`.

Anyway, I think for now it's best to keep things as they are, and simply pass the command your wish to execute in quoted form.

**Comment by rwstauner** [comment]
Not true.  With the original code, bash will run `touch` with no arguments (which will throw an error)
and the rest of the docker script won't run.
This change will at least run `touch hi there.txt`.  So it's not the command you expect, but at least the docker cleanup will be run.

Changing `$@` to `$*` means that the bash script you're wrapping the arguments with won't break if someone _does_ pass more than one argument.
With `$@` the command becomes `docker run bash -c "pre script; $1" "$2; post script"`
whereas with `$*` it becomes `docker run bash -c "pre script; $1 $2; post script"`

I was just trying to help prevent the situation where if someone doesn't realize that and passes a second argument, the post-script (`JOB_RESULT=\$? ; chown -R $(id -u`whoami`) /workspace; (exit \$JOB_RESULT)")` simply won't execute (because it ends up being passed as another argument to bash).

Here's another example of how it works:

``` bash
*$ cat ~/tmp/bashvars.sh
at   () { bash -c "echo before at;   $@; echo after at"; }
star () { bash -c "echo before star; $*; echo after star"; }

at echo breaks

star echo works

*$ bash ~/tmp/bashvars.sh
before at

before star
works
after star
```

It wasn't clear to me when I looked at it first but basically the api for this script is "pass a bash script as the sole argument".

Perhaps the best solution would be to abort early if more than one argument is passed.

**Comment by pascalw** [comment]
> Perhaps the best solution would be to abort early if more than one argument is passed.

Yes I agree. We can't fix this in a backwards compatible way but we can indeed abort if more than one argument is passed because in that case by definition what the user is trying to achieve won't work. I'll make the change in a separate PR.

Thanks for all the effort @rwstauner!

**Pull request closed without merging**
